name: Execute main script

on:
  schedule:
    - cron: "*/15 * * * *"

env:
  WIT_ACCESS_TOKEN: ${{secrets.WIT_ACCESS_TOKEN}}
  JOB_OFFER_REPLY_BODY: ${{secrets.JOB_OFFER_REPLY_BODY}}
  JOB_OFFER_REPLY_REMARKS: ${{secrets.JOB_OFFER_REPLY_REMARKS}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Create token.json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "token.json"
          json: ${{secrets.EMAIL_TOKEN}}
      - name: Execute script
        run: echo "Executing script"
